/* FILE NAME: RND.C
 * PROGRAMMER: AG6
 * DATE: 30.01.2019
 * PURPORSE: .
 */

#ifndef __UNIT_H_
#define __UNIT_H_

#include "def.h"
#include "anim.h"

ag6UNIT * AG6_AnimUnitCreateCow( VOID );
ag6UNIT * AG6_AnimUnitCreateCam( VOID );
ag6UNIT * AG6_AnimUnitCreateObjCow( VOID );
ag6UNIT * AG6_UnitCreateAxe( VOID );
ag6UNIT * AG6_AnimUnitCreateSphere( VOID );
ag6UNIT * AG6_AnimUnitCreateText( VOID );
ag6UNIT * AG6_UnitCreateGeom( VOID );
ag6UNIT * AG6_UnitCreateTess( VOID );
ag6UNIT * AG6_UnitCreateSphere( VOID );
ag6UNIT * AG6_UnitCreatePlane( VOID );

#endif /* __UNIT_H_ */


